version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: paymentservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d paymentservice"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: payment-gateway:latest
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/paymentservice
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      API_LOGIN_ID: your_authorize_net_login_id
      TRANSACTION_KEY: your_authorize_net_transaction_key
      JWT_SECRET: your_jwt_secret
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

