spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

authorize:
  net:
    api:
      login:
        id: ${API_LOGIN_ID}
    transaction:
      key: ${TRANSACTION_KEY}

jwt:
  secret: ${JWT_SECRET}
